[package]
name = "distributed-services"
version = "0.1.0"
edition = "2021"


[dependencies]
actix-web = "3"
bytes = "1"
pretty_env_logger = "0.4"
tokio = { version = "0.2", features = ["full"] }
tonic = { version = "0.6" }
